import { expect } from '@playwright/test'
import { test } from './fixtures'
import { checkLayout, openRome, tabTo } from './helpers'

// Mock data is reset by a fresh page for every test. No provider/network is required.
test.beforeEach(async ({ page }) => {
  await page.route('**/*', async (route) => {
    const url = new URL(route.request().url())
    if (url.hostname === '127.0.0.1' || url.hostname === 'localhost') await route.continue()
    else await route.abort()
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await expect(page.getByText('Rome with family', { exact: true })).toBeVisible()
})

test('main navigation and trip actions work from the keyboard with visible focus', async ({ page }) => {
  const map = page.getByRole('button', { name: 'Map', exact: true })
  await tabTo(page, map)
  await expect(map).toBeFocused()
  expect(await map.evaluate((element) => getComputedStyle(element).outlineStyle)).not.toBe('none')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'My photos', exact: true })).toBeVisible()
  await expect(page.getByText('11 photos on the map', { exact: true })).toBeVisible()
  await expect(page.getByText(/Shared with/)).toHaveCount(0)
  const dashboard = page.getByRole('button', { name: 'Dashboard', exact: true })
  await tabTo(page, dashboard)
  await page.keyboard.press('Enter')
  const open = page.locator('.trip-card').filter({ hasText: 'Rome with family' }).getByRole('button', { name: 'Open trip', exact: true })
  await tabTo(page, open)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Rome with family', exact: true })).toBeVisible()
  await tabTo(page, page.getByRole('button', { name: 'Journey', exact: true }))
  await page.keyboard.press('Space')
  await expect(page.getByRole('heading', { name: 'No capture date', exact: true })).toBeVisible()
})

test('pins activate with Enter and Space and photo navigation updates the counter', async ({ page }) => {
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await page.getByLabel('Trip', { exact: true }).selectOption('trip-europe')
  await expect(page.getByText('7 photos on the map', { exact: true })).toBeVisible()
  // Limit to one city: wider regional clusters differ legitimately by viewport.
  await page.getByRole('searchbox', { name: 'Filter my photos', exact: true }).fill('Paris')
  await expect(page.getByText('2 photos on the map', { exact: true })).toBeVisible()
  await tabTo(page, page.getByRole('button', { name: 'Zoom out', exact: true }))
  await page.keyboard.press('Enter')
  const cluster = page.getByRole('button', { name: '2 photos near Paris', exact: true })
  await expect(cluster).toBeVisible()
  await tabTo(page, cluster)
  await page.keyboard.press('Enter')
  const pin = page.getByRole('button', { name: 'Photo at Eiffel Tower, Paris', exact: true })
  await expect(pin).toBeVisible()
  await tabTo(page, pin)
  await page.keyboard.press('Space')
  const photos = page.getByRole('group', { name: 'Photos in Europe by rail', exact: true })
  await expect(photos).toBeVisible()
  await expect(photos.getByText('1 / 2')).toBeVisible()
  await tabTo(page, photos)
  await page.keyboard.press('ArrowRight')
  await expect(photos.getByText('2 / 2')).toBeVisible()
  await page.keyboard.press('ArrowLeft')
  await expect(photos.getByText('1 / 2')).toBeVisible()
  await tabTo(page, photos.getByRole('button', { name: 'Next photo', exact: true }))
  await page.keyboard.press('Enter')
  await expect(photos.getByText('2 / 2')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(photos).toHaveCount(0)
})

test('place search selects suggestions and Escape closes suggestions before correction', async ({ page }) => {
  await openRome(page)
  await tabTo(page, page.getByRole('button', { name: 'Set location', exact: true }))
  await page.keyboard.press('Enter')
  const search = page.getByRole('combobox', { name: 'Search for the place', exact: true })
  await expect(search).toBeFocused()
  await search.fill('Paris')
  await expect(page.getByRole('option', { name: 'Paris, France', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(search).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Save location', exact: true })).toBeVisible()
  await search.fill('Rome')
  await expect(page.getByRole('option', { name: 'Rome, Italy', exact: true })).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await tabTo(page, page.getByRole('button', { name: 'Save location', exact: true }))
  await page.keyboard.press('Enter')
  await expect(page.locator('.trip-saved')).toHaveText('Location saved: Rome, Italy.')
  await expect(page.getByRole('button', { name: 'Set location', exact: true })).toHaveCount(0)
  await expect(page.getByText('The capture time never changes;', { exact: false })).toHaveCount(0)
})

test('previous-photo location and Cancel are keyboard-accessible', async ({ page }) => {
  await openRome(page)
  await tabTo(page, page.getByRole('button', { name: 'Set location', exact: true }))
  await page.keyboard.press('Enter')
  await tabTo(page, page.getByRole('button', { name: 'Same place as previous photo', exact: true }))
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status').filter({ hasText: 'Same place as previous photo' })).toBeVisible()
  await tabTo(page, page.getByRole('button', { name: 'Cancel', exact: true }))
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Save location', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Set location', exact: true })).toBeVisible()
})

test('Dashboard, Map, Trip and correction fit the viewport', async ({ page }) => {
  await checkLayout(page)
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await expect(page.getByText('11 photos on the map', { exact: true })).toBeVisible()
  await checkLayout(page)
  if (page.viewportSize()!.width < 900) {
    const map = await page.locator('.mapscreen-map').boundingBox()
    const controls = await page.locator('.mp-filters').boundingBox()
    expect(controls!.y).toBeGreaterThan(map!.y + map!.height - 20)
  }
  await page.getByRole('button', { name: 'Dashboard', exact: true }).click()
  await openRome(page)
  await checkLayout(page)
  await page.getByRole('button', { name: 'Set location', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save location', exact: true })).toBeVisible()
  await checkLayout(page)
})
