import { test, expect } from './fixtures'
import { boot, openTrip, failNext, dashboard, checkLayout } from './helpers'

test('Trip gallery, journey, upload toggle, map and back controls work', async ({ page }) => {
  await boot(page)
  await openTrip(page, 'Rome with family')
  await expect(page.locator('.trip-tile')).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Gallery', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Journey', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Journey', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('heading', { name: 'No capture date', exact: true })).toBeVisible()
  await expect(page.locator('.trip-day')).toHaveCount(3)
  await page.getByRole('button', { name: 'Gallery', exact: true }).click()
  await expect(page.locator('.trip-tile')).toHaveCount(3)
  const upload = page.getByRole('button', { name: 'Upload photos', exact: true })
  await upload.click()
  await expect(upload).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.upl')).toBeVisible()
  await upload.click()
  await expect(page.locator('.upl')).toHaveCount(0)
  await page.getByRole('button', { name: 'Show on map', exact: true }).click()
  await expect(page.getByLabel('Trip', { exact: true })).toHaveValue('trip-rome')
  await dashboard(page)
  await openTrip(page, 'Rome with family')
  await page.locator('.trip-back').click()
  await expect(page.locator('.trip-card')).toHaveCount(3)
})

test('empty trip offers upload and empty journey without errors', async ({ page }) => {
  await boot(page, { scenario: 'empty-trip' })
  await openTrip(page, 'Empty trip')
  await expect(page.getByText('No photos in this trip yet.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Journey', exact: true }).click()
  await expect(page.getByText('No photos in this trip yet.', { exact: false })).toBeVisible()
  await page.locator('.trip-empty').getByRole('button', { name: 'Upload photos', exact: true }).click()
  await expect(page.locator('.upl input[type=file]')).toBeVisible()
})

for (const operation of ['getTrip', 'tripPhotos'] as const) {
  test(`Trip read failure (${operation}) offers retry and back`, async ({ page }) => {
    await boot(page)
    await failNext(page, operation)
    await page.getByRole('article', { name: 'Rome with family', exact: true }).getByRole('button', { name: 'Open trip' }).click()
    await expect(page.getByRole('alert')).toContainText('could not be loaded')
    await page.getByRole('button', { name: 'Try again' }).click()
    await expect(page.locator('.trip-tile')).toHaveCount(3)
    await page.locator('.trip-back').click()
    await expect(page.locator('.trip-card')).toHaveCount(3)
  })
}

test('all photo states have readable status and appropriate available actions', async ({ page }) => {
  await boot(page, { scenario: 'photo-states' })
  await openTrip(page, 'Rome with family')
  await expect(page.locator('.trip-tile')).toHaveCount(6)
  await expect(page.locator('.trip-status').filter({ hasText: 'Processing' })).toHaveCount(3)
  await expect(page.getByText('Upload failed', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Set location', exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Change location', exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Review place', exact: true })).toHaveCount(0)
})

test('all-undated journey keeps all photos in the undated section', async ({ page }) => {
  await boot(page, { scenario: 'undated' })
  await openTrip(page, 'Europe by rail')
  await page.getByRole('button', { name: 'Journey', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No capture date', exact: true })).toBeVisible()
  await expect(page.locator('.trip-day')).toHaveCount(1)
  await expect(page.locator('.trip-row')).toHaveCount(7)
})

test('Review next confirms suggestion without changing capture time, then targets missing location', async ({ page }) => {
  await boot(page)
  await openTrip(page, 'Rome with family')
  const original = await page.locator('.trip-tile').filter({ hasText: 'Pantheon, Rome' }).innerText()
  await page.getByRole('button', { name: 'Review next' }).click()
  await expect(page.getByRole('heading', { name: 'Review suggested place' })).toBeVisible()
  await page.getByRole('button', { name: 'Confirm Pantheon, Rome', exact: true }).click()
  await expect(page.locator('.trip-correct')).toHaveCount(0)
  await expect(page.locator('.trip-review')).toContainText('1 photo needs your review')
  await expect(page.locator('.trip-tile').filter({ hasText: 'Pantheon, Rome' })).toContainText('21 Sept 2026')
  expect(original).toContain('21 Sept 2026')
  await page.getByRole('button', { name: 'Review next' }).click()
  await expect(page.getByRole('heading', { name: 'Set location', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save location' })).toBeDisabled()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await dashboard(page)
  await expect(page.locator('.stat-tile-value').last()).toHaveText('1')
})

test('manual correction saves, updates totals and map, and retains capture metadata', async ({ page }) => {
  await boot(page)
  await openTrip(page, 'Rome with family')
  await page.getByRole('button', { name: 'Set location', exact: true }).click()
  await expect(page.locator('.trip-facts')).toContainText('No capture time in the file')
  const search = page.getByRole('combobox', { name: 'Search for the place' })
  await search.fill('Tokyo')
  await page.getByRole('option', { name: 'Tokyo, Japan' }).click()
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.locator('.trip-saved')).toContainText('Location saved')
  await expect(page.locator('.trip-tile').filter({ hasText: 'Tokyo' })).toContainText('No capture time')
  await page.getByRole('button', { name: 'Show on map' }).click()
  await expect(page.locator('.mp-count')).toHaveText('3 photos on the map')
  await dashboard(page)
  await expect(page.locator('.stat-tile-value')).toHaveText(['12', '6', '6', '1'])
})

test('failed correction retains chosen location and succeeds on retry', async ({ page }) => {
  await boot(page)
  await openTrip(page, 'Rome with family')
  await page.getByRole('button', { name: 'Set location', exact: true }).click()
  await page.getByRole('button', { name: 'Same place as previous photo' }).click()
  const chosen = await page.locator('.lpick-chosen').innerText()
  await failNext(page, 'patchLocation')
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.getByRole('alert')).toContainText('location could not be saved')
  await expect(page.locator('.lpick-chosen')).toHaveText(chosen)
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.locator('.trip-saved')).toContainText('Location saved')
  await expect(page.getByRole('button', { name: 'Set location', exact: true })).toHaveCount(0)
})

test('Change location can be cancelled without modifying the photo', async ({ page }) => {
  await boot(page)
  await openTrip(page, 'Rome with family')
  const tile = page.locator('.trip-tile').filter({ hasText: 'Colosseum' })
  const before = await tile.innerText()
  await tile.getByRole('button', { name: 'Change location' }).click()
  await expect(page.locator('.lpick-chosen')).toContainText('Current location')
  await page.getByRole('combobox', { name: 'Search for the place' }).press('Escape')
  // First Escape closes the focused search's suggestions; next closes correction.
  if (await page.locator('.trip-correct').count()) await page.keyboard.press('Escape')
  await expect(page.locator('.trip-correct')).toHaveCount(0)
  await expect(tile).toHaveText(before, { useInnerText: true })
})

test('map click and pin drag set coordinates and can be saved', async ({ page }) => {
  await boot(page)
  await openTrip(page, 'Rome with family')
  await page.getByRole('button', { name: 'Set location', exact: true }).click()
  const map = page.locator('.lpick-map')
  await map.click({ position: { x: 120, y: 120 } })
  await expect(page.locator('.lpick-chosen')).toContainText('Pin dropped on the map')
  const pin = page.locator('.lpick-pin')
  await pin.scrollIntoViewIfNeeded()
  const box = await pin.boundingBox()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await page.mouse.down()
  await page.mouse.move(box!.x + box!.width / 2 + 25, box!.y + box!.height / 2 + 20, { steps: 10 })
  await page.mouse.up()
  await expect(page.locator('.lpick-chosen')).toContainText('Pin moved on the map')
  await checkLayout(page)
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.locator('.trip-saved')).toContainText('Location saved')
})

test('loading status is shown while reading Dashboard, Map and Trip', async ({ page }) => {
  await boot(page, { delayMs: 600 })
  await expect(page.getByText('Loading your trips…')).toBeVisible()
  await expect(page.locator('.trip-card')).toHaveCount(3)
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: 'Map', exact: true }).click()
  await expect(page.getByText('Loading photos…')).toBeVisible()
  await expect(page.locator('.mp-count')).toBeVisible()
  await dashboard(page)
  await page.getByRole('article', { name: 'Rome with family', exact: true }).getByRole('button', { name: 'Open trip' }).click()
  await expect(page.getByText('Loading trip…')).toBeVisible()
  await expect(page.locator('.trip-tile')).toHaveCount(3)
})
